// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Suppress missing type declarations for dotenv in this environment
// @ts-ignore
import * as dotenv from "dotenv";
dotenv.config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use session-mode pooler (port 5432) for migrations.
    // Direct connections to db.*.supabase.co are unreachable from this network.
    // Transaction-mode pooler (port 6543) does not support DDL required by migrations.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
